# Generated by Django 2.0.6 on 2019-03-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0004_auto_20190313_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesidecontentmodel',
            name='SideBody',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='articlesidecontentmodel',
            name='SideTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
