# Generated by Django 2.0.6 on 2019-03-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0006_auto_20190313_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesidecontentmodel',
            name='SidePicture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='wikiarticlemodel',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='wikieditormodel',
            name='ProfilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
