# Generated by Django 2.0.6 on 2019-03-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0007_auto_20190313_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikiarticlemodel',
            old_name='LastEditted',
            new_name='LastEdited',
        ),
    ]
