# Generated by Django 2.0.6 on 2019-03-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0008_auto_20190314_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiarticlemodel',
            name='DateCreated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wikiarticlemodel',
            name='LastEdited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
