# Generated by Django 2.0.6 on 2019-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0010_auto_20190315_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiarticlemodel',
            name='Body',
            field=models.TextField(max_length=1000),
        ),
    ]
